name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install and build
      run: |
        yarn install
        yarn build
